# Generated by Django 4.0.4 on 2022-04-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('developedInto', models.TextField(max_length=50)),
                ('dob', models.TextField(max_length=50)),
                ('built', models.IntegerField()),
            ],
        ),
    ]
