# Generated by Django 4.0.4 on 2022-04-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='developedInto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='dob',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Fueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fuel', models.CharField(choices=[('B', 'Beginning of Flight'), ('M', 'Middle of Flight'), ('E', 'End of Flight')], default='B', max_length=1)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.aircraft')),
            ],
        ),
    ]
