# Generated by Django 4.0.4 on 2022-04-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_aircraft_developedinto_alter_aircraft_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fueling',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='fueling',
            name='date',
            field=models.DateField(verbose_name='Fueling Date'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='services',
            field=models.ManyToManyField(to='main_app.service'),
        ),
    ]
